<?php

/**
 * @file
 *   Acquia Cloud API securely communicates with your Acquia Cloud sites.
 */

/**
 * Implements function hook_registry_files_alter().
 */
function acquia_cloud_registry_files_alter(&$files, $modules) {

  $class_path = drupal_get_path('module', 'acquia_cloud') .'/lib';
  $class_files = file_scan_directory($class_path, '/\.(inc|php)$/');
  foreach (array_keys($class_files) as $file) {
    $files[$file] = array(
        'module' => 'acquia_cloud',
        'weight' => 0,
    );
  }
}

